version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
        --username bapan
        --firstname Bapan
        --lastname Bairagya
        --role Admin
        --email bapanmldl7892@gmail.com
        --password bapan@123
      "

  airflow-webserver:
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - postgres
      - redis
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__USE_JOB_SCHEDULE: "True"
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /requirements.txt"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../cfpb_project:/opt/airflow/cfpb_project
      - ../cfpb_project/.env:/opt/airflow/cfpb_project/.env
      - ./requirements.txt:/requirements.txt
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__USE_JOB_SCHEDULE: "True"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 5
      _PIP_ADDITIONAL_REQUIREMENTS: "-r /requirements.txt"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../cfpb_project:/opt/airflow/cfpb_project
      - ../cfpb_project/.env:/opt/airflow/cfpb_project/.env
      - ./requirements.txt:/requirements.txt
    command: scheduler

volumes:
  postgres-db-volume:
